export const sampleNotifications = [
  {
    priority: 100,
    date: "01/14/2019 16:10:53",
    name: "Dan Abrahmov",
    avatar: "https://bit.ly/dan-abramov",
    title:
      "A Banksy painting celebrating nurses as superheroes sells for a record-breaking $23M",
    message: "Lorem ipsum dolor sit amet",
    read: false,
  },
  {
    priority: 100,
    date: "01/14/2019 15:42:00",
    name: "Kola Tioluwani",
    avatar: "https://bit.ly/tioluwani-kolawole",
    title:
      "Note that even when the index is negative, the array is still searched from back to front",
    message:
      "The index at which to start searching backwards. Defaults to the array's length minus one (arr.length - 1), i.e. the whole array will be searched. If the index is greater than or equal to the length of the array, the whole array will be searched. If negative, it is taken as the offset from the end of the array. Note that even when the index is negative, the array is still searched from back to front. If the calculated index is less than 0, -1 is returned, i.e. the array will not be searched.",
    read: false,
  },
  {
    priority: 300,
    date: "01/25/2019 16:43:57",
    name: "Kent Dodds",
    avatar: "https://bit.ly/kent-c-dodds",
    title:
      "Americans spent the pandemic stocking up on booze. That may be changing",
    message: "Sed id sagittis erat",
    read: true,
  },
  {
    priority: 200,
    date: "02/02/2019 02:31:41",
    name: "Ryan Florence",
    avatar: "https://bit.ly/ryan-florence",
    title: "Your best refinance rates for March 2021",
    message: "Integer semper metus id mi tempor congue",
    read: false,
  },
  {
    priority: 100,
    date: "11/25/2019 14:41:13",
    name: "Prosper Otemuyiwa",
    avatar: "https://bit.ly/prosper-baba",
    title: "Taco Bell is getting a new look",
    message: "Donec blandit dapibus ultrices",
    read: true,
  },
  {
    priority: 100,
    date: "11/25/2019 04:41:58",
    name: "Christian Nwamba",
    avatar: "https://bit.ly/code-beast",
    title: "'American Idol' contestant faints after performance",
    message: "Donec blandit dapibus ultrices",
    read: true,
  },
  {
    priority: 100,
    date: "02/26/2020 04:03:51",
    name: "Segun Adebayo",
    avatar: "https://bit.ly/sage-adebayo",
    title:
      "Marvel's 'Black Widow' will debut on Disney+ and theaters at the same time",
    message: "Donec blandit dapibus ultrices",
    read: true,
  },
  {
    priority: 300,
    date: "01/12/2021 18:38:32",
    name: "Sasuke Uchiha",
    avatar: "https://bit.ly/broken-link",
    title: "Prince Harry lands a new job",
    message: "Donec blandit dapibus ultrices",
    read: true,
  },
  {
    priority: 100,
    date: "06/11/2022 22:54:55",
    avatar: "https://bit.ly/broken-link",
    title: "In a few words or less it can tell you what job the person does",
    message: "Donec blandit dapibus ultrices",
    read: true,
  },
  {
    priority: 100,
    date: "11/28/2022 02:16:52",
    name: "Some Name",
    avatar:
      "https://cdn.pixabay.com/photo/2021/03/03/08/56/woman-6064819_960_720.jpg",
    title: "Medical Assistant",
    message: "Donec blandit dapibus ultrices",
    read: true,
  },
];
