module.exports = [
  {
    name: "Services Parameter",
    services: [
      "Challenge Test",
      "Regulatory Services",
      "Microbiological Testing",
      "Graphic Design",
      "Regulatory Consultation",
      "Filling",
      "Cosmetic Product Testing",
      "Contract Manufacturing",
      "Packaging Services",
      "Formulation Development",
      "Ingredient Distributor",
      "Ingredient Manufacturing",
      "Labeling Services",
      "Testing Laboratory Services",
      "Private Label Manufacturing",
      "Cosmetic Product Development",
      "Cosmetic Project Consulting",
      "QA Services",
      "QC Services",
      "Packaging Distributor",
      "Safety Assessment",
      "Packaging Design",
    ],
  },
];
