module.exports =
{
 "Blue Island,IL,US": 1,
 "Chicago,IL,US": 8,
 "Northbrook,IL,US": 3,
 "Barrington,IL,US": 1,
 "Momence,IL,US": 1,
 "Ottawa,IL,US": 1,
 "Bloomingdale,IL,US": 1,
 "Skokie,IL,US": 1,
 "Carol Stream,IL,US": 1,
 "Waukegan,IL,US": 2,
 "Bolingbrook,IL,US": 1,
 "Quincy,IL,US": 1,
 "Woodstock,IL,US": 1,
 "Niles,IL,US": 1,
 "Glendale Heights,IL,US": 1,
 "Libertyville,IL,US": 2,
 "Cicero,IL,US": 2,
 "Dekalb,IL,US": 1,
 "Mount Prospect,IL,US": 1,
 "Franklin Park,IL,US": 1,
 "Willowbrook,IL,US": 1,
 "Addison,IL,US": 1,
 "Broadview,IL,US": 1,
 "Oak Lawn,IL,US": 1,
 "Hodgkins,IL,US": 1,
 "Rockford,IL,US": 1,
 "Hoffman Estates,IL,US": 1,
 "Hamilton,NJ,US": 1,
 "WEST BERLIN,NJ,US": 1,
 "Fort Lee,NJ,US": 2,
 "Edison,NJ,US": 3,
 "Ringwood,NJ,US": 1,
 "Newark,NJ,US": 2,
 "Springfield,NJ,US": 1,
 "Bridgewater,NJ,US": 2,
 "Linden,NJ,US": 1,
 "Totowa,NJ,US": 3,
 "Rockleigh,NJ,US": 1,
 "Glen Rock,NJ,US": 1,
 "Sayreville,NJ,US": 1,
 "Denville,NJ,US": 2,
 "Somerset,NJ,US": 2,
 "Lincoln Park,NJ,US": 1,
 "Lodi,NJ,US": 1,
 "Piscataway,NJ,US": 3,
 "Roselle,NJ,US": 1,
 "Paterson,NJ,US": 3,
 "Clifton,NJ,US": 2,
 "Westwood,NJ,US": 1,
 "Camden,NJ,US": 1,
 "Burlington,NJ,US": 1,
 "South Plainfield,NJ,US": 2,
 "Fairfield,NJ,US": 2,
 "Washington,NJ,US": 1,
 "Hillside,NJ,US": 1,
 "Monroe,NJ,US": 1,
 "Garwood,NJ,US": 1,
 "Secaucus,NJ,US": 1,
 "Cedar Grove,NJ,US": 1,
 "Irvington,NJ,US": 1,
 "Rockaway,NJ,US": 2,
 "Caldwell,NJ,US": 1,
 "Dayton,NJ,US": 1,
 "Norwood,NJ,US": 1,
 "Deptford,NJ,US": 1,
 "Hawthorne,NJ,US": 1,
 "Bayonne,NJ,US": 1,
 "Wayne,NJ,US": 1,
 "East Windsor,NJ,US": 1,
 "Boonton,NJ,US": 1,
 "Warren,NJ,US": 1,
 "Princeton,NJ,US": 1,
 "Pompton Plains,NJ,US": 1,
 "Somerville,NJ,US": 1,
 "Monmouth Junction,NJ,US": 2,
 "Fair Lawn,NJ,US": 1,
 "Passaic,NJ,US": 1,
 "Saddle Brook,NJ,US": 1,
 "Little Falls,NJ,US": 1,
 "Teterboro,NJ,US": 1,
 "Mahwah,NJ,US": 2,
 "Moonachie,NJ,US": 1,
 "Union,NJ,US": 1,
 "Asbury Park,NJ,US": 1,
 "Florham Park,NJ,US": 1,
 "Cinnaminson,NJ,US": 1,
 "EDISON,NJ,US": 1,
 "VERONA,NJ,US": 1,
 "Jackson,NJ,US": 1,
 "Montvale,NJ,US": 1,
 "North Brunswick,NJ,US": 1,
 "Lawrenceville,NJ,US": 1,
 "Rutherford,NJ,US": 1,
 "West Chester,PA,US": 3,
 "Newtown,PA,US": 1,
 "Petrolia,PA,US": 1,
 "East Stroudsburg,PA,US": 1,
 "Pittsburgh,PA,US": 1,
 "Warminster,PA,US": 1,
 "Conshohocken,PA,US": 1,
 "Philadelphia,PA,US": 3,
 "Morrisville,PA,US": 1,
 "Ivyland,PA,US": 1,
 "King Of Prussia,PA,US": 1,
 "Erie,PA,US": 1,
 "Willow Grove,PA,US": 1,
 "Pottstown,PA,US": 1,
 "Doylestown,PA,US": 1,
 "Morgantown,PA,US": 2,
 "Red Lion,PA,US": 1,
 "Bensalem,PA,US": 1,
 "Easton,PA,US": 1,
 "Fairview,PA,US": 1,
 "Spinnerstown,PA,US": 1,
 "Wyomissing,PA,US": 1,
 "Bethlehem,PA,US": 1,
 "Harrisburg,PA,US": 1,
 "Fort Lauderdale,FL,US": 3,
 "Ft. Lauderdale,FL,US": 1,
 "St Petersburg,FL,US": 3,
 "Tampa,FL,US": 2,
 "Miramar,FL,US": 1,
 "Miami,FL,US": 8,
 "Deerfield Beach,FL,US": 1,
 "Bartow,FL,US": 1,
 "Sunrise,FL,US": 2,
 "Plantation,FL,US": 1,
 "Sarasota,FL,US": 1,
 "Hialeah,FL,US": 2,
 "Ormond beach,FL,US": 1,
 "Saint Petersburg,FL,US": 1,
 "Hallandale Beach,FL,US": 1,
 "Miami Gardens,FL,US": 1,
 "Melbourne,FL,US": 2,
 "Bunnell,FL,US": 1,
 "Boca Raton,FL,US": 3,
 "Ponte Vedra Beach,FL,US": 1,
 "Coral Gables,FL,US": 1,
 "Pompano Beach,FL,US": 2,
 "St. Petersburg,FL,US": 1,
 "Fort Myers,FL,US": 1,
 "Weston,FL,US": 2,
 "Orlando,FL,US": 2,
 "Doral,FL,US": 1,
 "Fort Pierce,FL,US": 1,
 "MIAMI,FL,US": 1,
 "Tampa/St. Petersburg,FL,US": 1,
 "Medley,FL,US": 1,
 "Ocala,FL,US": 1,
 "New York,NY,US": 11,
 "Port Washington,NY,US": 2,
 "Farmingdale,NY,US": 6,
 "Sherburne,NY,US": 1,
 "Mamaroneck,NY,US": 1,
 "Jamaica,NY,US": 1,
 "Stony Brook,NY,US": 1,
 "Kings Point,NY,US": 1,
 "Freeport,NY,US": 1,
 "Lindenhurst,NY,US": 1,
 "Mount Vernon,NY,US": 1,
 "Islandia,NY,US": 1,
 "Edgewood,NY,US": 1,
 "Ronkonkoma,NY,US": 2,
 "Dix Hills,NY,US": 1,
 "Long Island City,NY,US": 1,
 "Syracuse,NY,US": 1,
 "Brooklyn,NY,US": 3,
 "Huntington,NY,US": 1,
 "West Babylon,NY,US": 1,
 "Rochester,NY,US": 2,
 "Far Rockaway,NY,US": 1,
 "Oneonta,NY,US": 1,
 "Holtsville,NY,US": 1,
 "New York City,NY,US": 1,
 "Highland,NY,US": 1,
 "Staten Island,NY,US": 1,
 "Bronx,NY,US": 1,
 "Plattsburgh,NY,US": 1,
 "Norwich,NY,US": 1,
 "Monticello,NY,US": 1,
 "Ridgewood,NY,US": 1,
 "Commack,NY,US": 1,
 "Troy,NY,US": 1,
 "Port Chester,NY,US": 1,
 "West Seneca,NY,US": 1,
 "Shirley,NY,US": 1,
 "New City,NY,US": 1,
 "Chester,NY,US": 1,
 "Boulevard,NY,US": 1,
 "Long Island,NY,US": 1,
 "New Windsor,NY,US": 1,
 "Mineola,NY,US": 1,
 "Copiague,NY,US": 1,
 "Queens,NY,US": 1,
 "San Francisco,CA,US": 1,
 "Los Angeles,CA,US": 3,
 "Fontana,CA,US": 1,
 "Downey,CA,US": 1,
 "Chatsworth,CA,US": 8,
 "Carson,CA,US": 4,
 "Fullerton,CA,US": 2,
 "Aoura Hills,CA,US": 1,
 "SUN VALLEY,CA,US": 1,
 "Ontario,CA,US": 3,
 "Commerce,CA,US": 3,
 "Victorville,CA,US": 1,
 "Cerritos,CA,US": 1,
 "Lake Forest,CA,US": 1,
 "Camarillo,CA,US": 1,
 "Santa Ana,CA,US": 5,
 "Corning,CA,US": 1,
 "Walnut,CA,US": 1,
 "Chino,CA,US": 3,
 "Gardena,CA,US": 3,
 "Emeryville,CA,US": 2,
 "San Diego,CA,US": 9,
 "Mira Loma,CA,US": 1,
 "San Bernardino,CA,US": 2,
 "Riverside,CA,US": 3,
 "Van Nuys,CA,US": 1,
 "Fountain Valley,CA,US": 2,
 "Redlands,CA,US": 1,
 "San Leandro,CA,US": 2,
 "San Marcos,CA,US": 1,
 "Corona,CA,US": 3,
 "Orange,CA,US": 4,
 "Newbury Park,CA,US": 1,
 "Placentia,CA,US": 1,
 "Newport Beach,CA,US": 1,
 "North Hollywood,CA,US": 1,
 "Santa Fe Springs,CA,US": 2,
 "Torrance,CA,US": 4,
 "Pomona,CA,US": 1,
 "Anaheim,CA,US": 9,
 "Poway,CA,US": 1,
 "Sylmar,CA,US": 1,
 "Lancaster,CA,US": 1,
 "Santa Clarita,CA,US": 2,
 "Valencia,CA,US": 1,
 "Hayward,CA,US": 3,
 "San Luis Obispo,CA,US": 1,
 "Lakewood,CA,US": 1,
 "City of Industry,CA,US": 1,
 "Hemet,CA,US": 1,
 "Fremont,CA,US": 3,
 "Brea,CA,US": 1,
 "Tustin,CA,US": 2,
 "Santa Monica,CA,US": 2,
 "Merced,CA,US": 1,
 "Oxnard,CA,US": 2,
 "Arcadia,CA,US": 2,
 "South San Francisco,CA,US": 1,
 "La Puente,CA,US": 1,
 "La Habra,CA,US": 1,
 "Rancho Cucamonga,CA,US": 1,
 "Compton,CA,US": 1,
 "Irvine,CA,US": 2,
 "San Bernadino,CA,US": 1,
 "Montebello,CA,US": 1,
 "Del Mar,CA,US": 1,
 "San Dimas,CA,US": 1,
 "South El Monte,CA,US": 1,
 "Livermore,CA,US": 2,
 "Calabasas,CA,US": 1,
 "Murrieta,CA,US": 1,
 "Huntington Beach,CA,US": 1,
 "Berkeley,CA,US": 1,
 "Monterey Park,CA,US": 1,
 "Watsonville,CA,US": 1,
 "South Gate,CA,US": 1,
 "Glendale,CA,US": 1,
 "Northridge,CA,US": 1,
 "Paso Robles,CA,US": 1,
 "Sun Valley,CA,US": 1,
 "AZUSA,CA,US": 1,
 "Corona,CA,Us": 1,
 "South Pasadena,CA,US": 1,
 "LAKE FOREST,CA,US": 1,
 "Laguna Hills,CA,US": 1,
 "Burbank,CA,US": 1,
 "Sherman Oaks,CA,US": 1,
 "Eagan,MN,US": 1,
 "Chanhassen,MN,US": 1,
 "Minnetonka,MN,US": 1,
 "Eden Prairie,MN,US": 1,
 "West Saint Paul,MN,US": 1,
 "Lake City,MN,US": 1,
 "Edgerton,MN,US": 1,
 "Blaine,MN,US": 1,
 "Shoreview,MN,US": 1,
 "Winchester,VA,US": 1,
 "Richmond,VA,US": 2,
 "Lexington,VA,US": 1,
 "Alexandria,VA,US": 1,
 "Reston,VA,US": 1,
 "Gainesville,VA,US": 1,
 "Louisville,KY,US": 2,
 "Campton,KY,US": 1,
 "Kent,WA,US": 1,
 "Redmond,WA,US": 1,
 "Blaine,WA,US": 1,
 "Lakewood,WA,US": 1,
 "Spokane,WA,US": 1,
 "McAllen,TX,US": 1,
 "Keller,TX,US": 1,
 "Carrollton,TX,US": 5,
 "Pearland,TX,US": 1,
 "Katy,TX,US": 1,
 "Dallas,TX,US": 11,
 "Farmers Branch,TX,US": 1,
 "Houston,TX,US": 6,
 "Kaufman,TX,US": 1,
 "Fort Worth,TX,US": 1,
 "Friendswood,TX,US": 1,
 "Irving,TX,US": 4,
 "Sugar Land,TX,US": 1,
 "Austin,TX,US": 1,
 "Athens,TX,US": 1,
 "The Woodlands,TX,US": 1,
 "Round Rock,TX,US": 2,
 "Del Valle,TX,US": 1,
 "Ft. Worth,TX,US": 1,
 "Garland,TX,US": 1,
 "Richmond,TX,US": 1,
 "Lansing,MI,US": 1,
 "Farmington Hills,MI,US": 2,
 "Troy,MI,US": 1,
 "Macomb,MI,US": 1,
 "Livonia,MI,US": 2,
 "Grand Rapids,MI,US": 2,
 "Plymouth,MI,US": 1,
 "Alma,MI,US": 1,
 "Saline,MI,US": 1,
 "Ann Arbor,MI,US": 1,
 "Midland,MI,US": 1,
 "SOUTHFIELD,MI,US": 1,
 "Wausau,WI,US": 1,
 "Lake Geneva,WI,US": 1,
 "Madison,WI,US": 3,
 "Milwaukee,WI,US": 2,
 "Richfield,WI,US": 1,
 "Green Bay,WI,US": 1,
 "Neenah,WI,US": 2,
 "Cross Plains,WI,US": 1,
 "Menomonee Falls,WI,US": 1,
 "Racine,WI,US": 1,
 "Lannon,WI,US": 1,
 "Oak Harbor,OH,US": 1,
 "Cincinnati,OH,US": 4,
 "Wadsworth,OH,US": 2,
 "Cleveland,OH,US": 2,
 "Milford,OH,US": 1,
 "Loveland,OH,US": 1,
 "Toledo,OH,US": 1,
 "Avon,OH,US": 1,
 "Glenwillow,OH,US": 1,
 "Twinsburg,OH,US": 1,
 "Newark,OH,US": 1,
 "Mentor,OH,US": 1,
 "Brecksville,OH,US": 1,
 "Wickliffe,OH,US": 1,
 "Solon,OH,US": 1,
 "Macedonia,OH,US": 1,
 "Draper,UT,US": 2,
 "Salt Lake City,UT,US": 1,
 "Orem,UT,US": 2,
 "Provo,UT,US": 1,
 "Vineyard,UT,US": 1,
 "Milford,CT,US": 1,
 "Stamford,CT,US": 1,
 "Naugatuck,CT,US": 1,
 "Fairfield,CT,US": 1,
 "Versailles,CT,US": 1,
 "Putnam,CT,US": 1,
 "Sandy Hook,CT,US": 1,
 "Norwalk,CT,US": 1,
 "Torrington,CT,US": 1,
 "Berlin,CT,US": 1,
 "Dickson,TN,US": 1,
 "La Vergne,TN,US": 1,
 "Chattanooga,TN,US": 2,
 "Greeneville,TN,US": 1,
 "Nashville,TN,US": 1,
 "Memphis,TN,US": 1,
 "Braintree,MA,US": 1,
 "Salem,MA,US": 1,
 "Waltham,MA,US": 1,
 "Easton,MA,US": 1,
 "Fitchburg,MA,US": 1,
 "Framingham,MA,US": 2,
 "Mansfield,MA,US": 1,
 "Boxborough,MA,US": 1,
 "Wilmington,MA,US": 1,
 "Shrewsbury,MA,US": 1,
 "Woburn,MA,US": 1,
 "Taunton,MA,US": 1,
 "Steamboat Springs,CO,US": 1,
 "Northglenn,CO,US": 1,
 "Denver,CO,US": 1,
 "Englewood,CO,US": 1,
 "Parker,CO,US": 1,
 "Prosperity,SC,US": 1,
 "Hartsville,SC,US": 1,
 "Dalzell,SC,US": 1,
 "Johns Island,SC,US": 1,
 "Eugene,OR,US": 1,
 "Portland,OR,US": 2,
 "Russellville,AL,US": 1,
 "Smyrna,GA,US": 1,
 "Atlanta,GA,US": 2,
 "Lawrenceville,GA,US": 2,
 "Austell,GA,US": 1,
 "Norcross,GA,US": 2,
 "Research Triangle Park,NC,US": 1,
 "Raleigh,NC,US": 1,
 "Fletcher,NC,US": 1,
 "Hickory,NC,US": 1,
 "Charlotte,NC,US": 1,
 "Asheboro,NC,US": 1,
 "Wilson,NC,US": 1,
 "Durham,NC,US": 1,
 "St John,VI,US": 1,
 "Indianapolis,IN,US": 2,
 "Michigan City,IN,US": 1,
 "Bedford,IN,US": 1,
 "South Bend,IN,US": 1,
 "Evanston,WY,US": 1,
 "Jackson,WY,US": 1,
 "Lincoln,RI,US": 1,
 "Pawtucket,RI,US": 1,
 "East Greenwich,RI,US": 1,
 "Providence,RI,US": 1,
 "West Warwick,RI,US": 1,
 "Scottsdale,AZ,US": 2,
 "Phoenix,AZ,US": 2,
 "Tempe,AZ,US": 1,
 "Chandler,AZ,US": 2,
 "Gilbert,AZ,US": 1,
 "Madrid,IA,US": 1,
 "Lancaster,NH,US": 1,
 "Hinsdale,NH,US": 1,
 "Nashua,NH,US": 1,
 "Idaho Falls,ID,US": 1,
 "Hansen,ID,US": 1,
 "Bonners Ferry,ID,US": 1,
 "Lawton,OK,US": 1,
 "Inola,OK,US": 1,
 "Seminole,OK,US": 1,
 "Meridian,MS,US": 1,
 "Baltimore,MD,US": 6,
 "Owings Mills,MD,US": 1,
 "Ellicott City,MD,US": 1,
 "Glen Burnie,MD,US": 1,
 "Linthicum Heights,MD,US": 1,
 "Park Hills,MO,US": 1,
 "Arnold,MO,US": 1,
 "Columbia,MO,US": 1,
 "Saint Louis,MO,US": 1,
 "Sullivan,MO,US": 1,
 "Louis,MO,US": 1,
 "Lawrence,KS,US": 1,
 "Las Vegas,NV,US": 2,
 "Omaha,NE,US": 1,
 "Wilmington,DE,US": 1,
 "Kirkwood,DE,US": 1,
 "Bozeman,MT,US": 1,
 "Essex Junction,VT,US": 1,
 "Westfield,VT,US": 1,
 "Winooski,VT,US": 1,
 "Taos,NM,US": 1,
 "Albuquerque,NM,US": 1,
 "Washington,DC,US": 1,
 "Honolulu,HI,US": 1
}
