module.exports =
{
 "Contract Manufacturing": 206,
 "Formulation Development": 106,
 "Packaging Services": 191,
 "Custom Formulation": 46,
 "Cosmetic Brand Development": 8,
 "Packaging Manufacturing": 256,
 "Packaging Distributor": 47,
 "Packaging Printing": 46,
 "Graphic Design": 14,
 "Packaging Design": 51,
 "Cosmetic Product Development": 46,
 "Private Label Manufacturing": 85,
 "Cosmetic Project Consulting": 2,
 "Labeling Services": 27,
 "Filling": 83,
 "Packaging Samples": 3,
 "Cosmetic Product Testing": 29,
 "Ingredient Manufacturing": 65,
 "Ingredient Distributor": 41,
 "Clinical Testing of Cosmetics": 1,
 "Regulatory Services": 27,
 "QC Services": 3,
 "Label Design": 8,
 "Product Development": 1,
 "Stock Formulation": 5,
 "Formulation Services": 3,
 "QA Services": 2,
 "Secondary Packaging": 6,
 "Powder Filling": 1,
 "Foil Packaging": 3,
 "Die Cut Packaging": 1,
 "Folding Carton Gluing": 1,
 "Plastic Packaging Services": 2,
 "Protective Packaging": 1,
 "Corrugated Packaging": 1,
 "Cosmetic Packaging": 1,
 "Custom Cannabis Packaging": 1,
 "Cosmetic Cello Wrapping": 1,
 "Aerosol Packaging": 1,
 "Stock Packaging": 3,
 "Flow Wrap Packaging": 1,
 "Microbiological Testing": 11,
 "Toxicology Testing": 6,
 "Regulatory Compliance Services": 3,
 "Stability Testing": 10,
 "Performance Testing": 1,
 "Child Resistant Packaging": 1,
 "Sterility Testing": 2,
 "Liquid Chromatography Analysis": 1,
 "Gas Chromatography Analysis": 1,
 "Mass Spectrometry": 1,
 "Elemental Analysis": 1,
 "Thermal Analysis": 1,
 "Cleaning Validation": 1,
 "Cosmetic Development Process Validation": 1,
 "Cosmetic Product Analysis": 1,
 "Bioburden Testing": 2,
 "Safety Assessment": 10,
 "Testing Services": 34,
 "Regulatory Consultation": 1,
 "Challenge Test": 16,
 "Certifications": 1,
 "Residual Testing": 1,
 "Environmental Monitoring": 1,
 "Custom Product Testing": 1,
 "Fillling": 1,
 "Chemical Testing": 1,
 "White Label Manufacturing": 1,
 "Cosmetic Testing": 1,
 "Raw Material Quality Assurance": 1,
 "Safety Testing": 2,
 "Product Characterization": 1,
 "Product Substrate Interaction Studies": 1,
 "Consulting Services": 1,
 "Formulation Developement": 1,
 "Licensed Intellectual Property": 1,
 "Patent Consulting": 1,
 "Claim Substantiation": 1,
 "Cosmetic Product Development.Testing Services": 1,
 "Custom formulation": 1,
 "Cosmetic Product  Development": 1,
 "Custom Manufacturing": 1,
 "Marketing Services": 2,
 "Private": 1,
 "Formulation development": 2,
 "Contract  Manufacturing": 2,
 "Private Label Manufaturing": 2,
 "Label Review": 8,
 "Formulation Review": 1,
 "Formula Review": 1,
 "Ingredients Review": 1
}
